### ISSUE TITLE
BTD Battles bot doesn't work

### ISSUE THREAD

**Issue by terminalarch** [GlennnM/NKFlashServers#1]
I changed the connection info from the NK server to localhost, but trying to run Bloon Terminator resulted in a crash saying the server actively refused the connection. The repo to the bot is archived so I can't ask there, so sorry if this is unrelated

**Comment by GlennnM** [comment]
It wouldn't be localhost if you are using the one installed by the powershell scripts, you would have to change it to the server ip it's being hosted on rn

**Comment by terminalarch** [comment]
I'm a bit confused. I tried using multiple addresses (127.0.0.1, my network IP, external IP, etc..). I tried using Fiddler to connect to your server, but after that it ended up not connected to the server, though I likely got something wrong

**Comment by terminalarch** [comment]
Adding: Hosted the server on a VPS and made a new swf, auto responder rule, still didn't connect whatsoever

**Comment by terminalarch** [comment]
Alr I'm dumb. I thought the installation was for local hosting, but it was connecting to your server. Realized that when pasting 154.53.49.118 as the connection url
